language: node_js
node_js:
- '7'
- '6'
cache: yarn
deploy:
  provider: npm
  email: zephraph@gmail.com
  api_key:
    secure: H42eItxzfF/PM5vkszdKa5B4tyiBNu85UGskDf71CINy4UlWB6Zvba4Jr2LkApp8UJdOXOk4D4coL/Hn5iKMADJUG+GKuUOwUW3vqo6XqoLIrIqLCXtPSg6JUmauAvycGHMvcQOmQrHhZ+3DwkkhJdkxO5pl4D/zhgFeLBA3gOHXxd95pGQlYuYQVrny0K446/CPSs3K2oU4eqveDBy3tc0kDq5jjU6kjgm4ogp1VIT9L4bezpnO00hY0h8pxAPZ2l0B57DYzDhUkfKn/A/oUEbJqQu+aK0fDStaWRzSzFdSkfvPRY1NHWR5mUUhLk5ODQpMSHbUoZ7Si1MVIDfxEVabzYgfRRNPzQJS9TX8v/DgE2ksrck4EajxAR9UOk2/fE6HwH1A5Ov6KYtP0OAFsr0Ex8VX1B7hm9yjaD2XKpJJIXo+NfNSEYWtCXL4mqcGEFcmhXYcw5k78PBk8nLzv+Em93m4Uc3Ldh+JpduUyv+cLCC5H7wuQlf1r3d0sDnpEb0JGaDHrp9+V1/i5noYqY0LRXZ87BuEmDgnUzUQR+fHNHXwMFlHLwi0G5Nmjc1Cksr6bpBtYvxXbOXB0CtkQBr+jOM+0I3iWFTzvjuVis8D8ls1g+IfnXItQj8Wa7bySJelapwFePaoH9ew7XTUreh48CMWvxO2vf4q8Lq2OF4=
  on:
    branch: master
    tags: true
    repo: zephraph/vue-theme-loader
