language: node_js
node_js:
- '7'
- '6'
cache: yarn
deploy:
  provider: npm
  email: zephraph@gmail.com
  api_key:
    secure: T88oNoFcrWyozmNB+xxu2CAcfvZLt9CrfdRY8kovmKKS6vA5DIW+vsVjeUHK9IFplBw4ZvfGMGn1ymaBn/v5DrrmKRVxtwBwU/r7/jcNceMIISydN1MSyxE7VUlfn4fcErXjra7y7ZssFnryatqKHWeV9FdRG/68mIkxphMM80r7wXo7sh0SJmkZztCFgZsQAE2K/X0Q5KXEIj0i0tHC1cYdSNgmvCDmlYecqu70tRgTvt3Siz09aYcY++bnimrKYU9fQl/RaFpy4Qphb60u/+M8Uizw98KDRkMD0qSUV1+O0hgRj2bp7A90vJso2j9EDqbQOpZbcY6Fq/6hU3O0KsnU/XfpFd/fVsOjNd4WztbmTTsRM5XUZwWLKg3DqRDSX73Z1ZdmKQ/Vb3vzmn0Jm4WfEtEpHQx5gHcqUeneM/57ZWPDJlCX5gHCnO/smsS8eRSteSvH41XsRlUBPvwPEKR4C3T2X7341qeWjKYGicefgnPC9RK2ePzAsKhQQymHoUqlHULfDv5ysKP+xP2031bm3kwkmBntiK9ee/2UHEBycd5sP2BZH8x+Klgdr3iJ8dpjC936X9T90w8uoUFvsfJKRLGtNMI6DFNzDzvYZSoUE2QCbXrhM+NeEBwKh0QiyCR9c9Ve1QUIrxxxOC+hlNd4LPsSgUl9yzxO6PvkP1M=
  on:
    branch: master
    tags: true
    repo: zephraph/vue-theme-loader
